name: 'Tag Release'
description: 'Create and push git tag'
author: 'whooof'

inputs:
  tag:
    description: 'Tag name'
    required: true
  message:
    description: 'Tag message (default: Release {tag})'
    required: false
    default: ''
  push:
    description: 'Push tag to remote'
    required: false
    default: 'true'
  commit_files:
    description: 'Files to commit before tagging (space-separated)'
    required: false
    default: ''
  commit_message:
    description: 'Commit message'
    required: false
    default: ''
  git_user_name:
    description: 'Git user name'
    required: false
    default: 'github-actions[bot]'
  git_user_email:
    description: 'Git user email'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'

runs:
  using: 'composite'
  steps:
    - name: Configure git
      shell: bash
      run: |
        git config user.name "$GIT_USER_NAME"
        git config user.email "$GIT_USER_EMAIL"
      env:
        GIT_USER_NAME: ${{ inputs.git_user_name }}
        GIT_USER_EMAIL: ${{ inputs.git_user_email }}

    - name: Commit changes
      if: inputs.commit_files != ''
      shell: bash
      run: |
        # Safely add files (split by whitespace)
        for file in $COMMIT_FILES; do
          if [ -f "$file" ]; then
            git add "$file"
          else
            echo "Warning: File not found: $file"
          fi
        done
        COMMIT_MSG="$INPUT_COMMIT_MESSAGE"
        if [ -z "$COMMIT_MSG" ]; then
          COMMIT_MSG="Release $INPUT_TAG"
        fi
        git commit -m "$COMMIT_MSG" || echo "Nothing to commit"
      env:
        COMMIT_FILES: ${{ inputs.commit_files }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit_message }}
        INPUT_TAG: ${{ inputs.tag }}

    - name: Create tag
      shell: bash
      run: |
        TAG_MSG="$INPUT_MESSAGE"
        if [ -z "$TAG_MSG" ]; then
          TAG_MSG="Release $INPUT_TAG"
        fi
        git tag -a "$INPUT_TAG" -m "$TAG_MSG"
      env:
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_MESSAGE: ${{ inputs.message }}

    - name: Push changes and tag
      if: inputs.push == 'true'
      shell: bash
      run: |
        git push origin HEAD
        git push origin "$INPUT_TAG"
      env:
        INPUT_TAG: ${{ inputs.tag }}
