# Rust project with universal binary (arm64 + x86_64)
# Builds for both architectures and creates a universal .app bundle

name: Release Universal

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-action@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/myapp

  release:
    needs: build
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download arm64 binary
        uses: actions/download-artifact@v4
        with:
          name: binary-aarch64-apple-darwin
          path: target/aarch64-apple-darwin/release

      - name: Download x86_64 binary
        uses: actions/download-artifact@v4
        with:
          name: binary-x86_64-apple-darwin
          path: target/x86_64-apple-darwin/release

      - name: Release
        uses: whooof/macos-release-action@v1
        with:
          release_type: ${{ inputs.release_type }}
          update_cargo: true
          update_plist: true
          create_bundle: true
          app_name: MyApp
          architecture: universal
          arm64_binary: target/aarch64-apple-darwin/release/myapp
          x86_64_binary: target/x86_64-apple-darwin/release/myapp
          binary_path: target/release/myapp
          plist_path: Info.plist
          icon_path: assets/icon.icns
          create_release: true
