name: 'GitHub Release'
description: 'Create GitHub Release'
author: 'whooof'

inputs:
  tag:
    description: 'Tag name'
    required: true
  name:
    description: 'Release name (default: tag)'
    required: false
    default: ''
  body:
    description: 'Release body'
    required: false
    default: ''
  files:
    description: 'Files to attach (glob pattern)'
    required: false
    default: ''
  draft:
    description: 'Create as draft'
    required: false
    default: 'false'
  prerelease:
    description: 'Mark as prerelease (auto = detect from version)'
    required: false
    default: 'auto'
  generate_notes:
    description: 'Generate release notes'
    required: false
    default: 'true'

outputs:
  release_url:
    description: 'URL to the release'
    value: ${{ steps.release.outputs.url }}
  upload_url:
    description: 'URL for uploading assets'
    value: ${{ steps.release.outputs.upload_url }}

runs:
  using: 'composite'
  steps:
    - name: Determine prerelease
      id: prerelease
      shell: bash
      run: |
        if [ "$INPUT_PRERELEASE" = "auto" ]; then
          if [[ "$INPUT_TAG" == *"-"* ]]; then
            echo "value=true" >> $GITHUB_OUTPUT
          else
            echo "value=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "value=$INPUT_PRERELEASE" >> $GITHUB_OUTPUT
        fi
      env:
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_PRERELEASE: ${{ inputs.prerelease }}

    - name: Create release
      id: release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.tag }}
        name: ${{ inputs.name || inputs.tag }}
        body: ${{ inputs.body }}
        files: ${{ inputs.files }}
        draft: ${{ inputs.draft }}
        prerelease: ${{ steps.prerelease.outputs.value }}
        generate_release_notes: ${{ inputs.generate_notes }}
